
const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/routes/index',
                        './src/routes/user' ];

swaggerAutogen(outputFile, endpointsFiles);

const doc = {
  info: {
      version: "1.0.0",
      title: "TCC - Rest Api",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    JWT: {
      description: 'JWT token',
      type: 'apiKey',
      in: 'header',
      name: 'Authorization',
    },
  },
  tags: [
    {
      "name": "Index",
      "description": "Views"
    },
    {
      "name": "User",
      "description": "Rota do usuário"
    }
  ],
  definitions:{
    Index: {
      description: "Nessa rota ficara as views da API"
    }
  },
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./Server')
})

