const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json';
const endpointsFiles = [ './index' ];

swaggerAutogen(outputFile, endpointsFiles);

const doc = {
  info: {
      version: "1.0.0",
      title: "TCC - Rest Api",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    JSONWebToken: {
      description: 'JSON Web Token',
      type: 'apiKey',
      in: 'header',
      name: 'auth-token',
    },
  },
  tags: [
    {
      "name": "User",
      "description": "Rota do usuário"
    }
  ],
  definitions:{
    User: {
      id: 1,
      name: "username",
      email: "username@example.com",
      password: "password",
      role: 1
    },
    Role: {
      id: 1,
      name: "role",
    },
    Report: {
      id: 1,
      title: "Report Title",
      dir: "/diretorio/report title.sql",
      role: 1,
    },
  },
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./index')
})

